language: generic

notifications:
  email: false

services:
 - docker

env:
  global:
   - MAKEJOBS = -j4
  matrix:
   - CC=gcc IMAGE=voidlinux/voidlinux DEPENDENCY_PACKAGES="bash kyua zlib-devel libarchive-devel base-devel atf-devel"
   - CC=clang IMAGE=voidlinux/voidlinux DEPENDENCY_PACKAGES="clang bash kyua zlib-devel libarchive-devel base-devel atf-devel"
   - CC=gcc IMAGE=voidlinux/voidlinux-musl DEPENDENCY_PACKAGES="bash kyua zlib-devel libarchive-devel base-devel atf-devel"
   - CC=clang IMAGE=voidlinux/voidlinux-musl DEPENDENCY_PACKAGES="clang bash kyua zlib-devel libarchive-devel base-devel atf-devel"

install:
 - docker pull "$IMAGE"
 - docker run -v "$PWD":/tmp/build-dir "$IMAGE" /bin/sh -c "xbps-install -Syu && xbps-install -y $DEPENDENCY_PACKAGES && cd /tmp/build-dir && CC=$CC ./configure --enable-tests --enable-debug && make $MAKEJOBS && make check"

script:
 - echo BUILDS PASSED
