sudo:     required
dist:     trusty
language: c
compiler:
        - gcc
        - clang

env:
        - PKG_CONFIG_PATH=/usr/local/lib/pkgconfig

before_install:
        - ./admin/travis-install-deps.sh

script:
        - LDFLAGS="-L/usr/local/lib -Wl,-R/usr/local/lib" ./configure --enable-tests --enable-debug && make -j16 && make check
